name: Deploy Infra AWS

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  BUCKET_NAME: postech-fiap-fastfood-backend-eks-lino #trocar o nome do bucket

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Create S3 Backend Bucket if it doesn't exist
        id: create-bucket
        run: |
          aws s3 mb s3://${{ env.BUCKET_NAME }} --region us-east-1 || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id: apply
        run: |
          cd infra 
          terraform fmt
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
